### ISSUE TITLE
Publish new release on Packagist

### ISSUE THREAD

**Issue by styxit** [xolphin/xolphin-api-php#13]
The releases on Packagist and GitHub are not in sync.
I would like to use the option to get "notes" that has been made available in release `1.6.2`, but that can not be installed via composer because this release is not published on Packagist.

- The latest release on GitHub is `1.6.2` released on Apr 12, 2018.
- The latest release on Packagist is `1.6.1` released on Dec 12, 2017.

And maybe setup auto-publishing for Packagist?
https://packagist.org/about#how-to-update-packages

**Comment by XolphinIvo** [comment]
Hi, we've been very busy lately with all kinds of updates. A new version of our API (and wrappers) will be released soon (approximately somewhere in the next month). We will update the packages here, and also on packagist.

**Comment by styxit** [comment]
The latest version on Packagist is still not up to date with the current tagged release here at GitHub. I would like to use the new Notes feature released in v1.6.2, but the latest version on Packagist is v1.6.1

**Comment by XolphinIvo** [comment]
I will check with the owner of the Packagist repository if I can get the proper permissions to setup autopublish to prevent this in the future.

Also, a new release is pending to support all functionality up to and including v1.8 of our API.

**Comment by robbinjanssen** [comment]
@XolphinIvo any update on contacting the owner? :-)

**Comment by XolphinIvo** [comment]
Yes. Both me and my colleague can now update packagist. At this time Packagist won't (auto) update since the composer.json wasn't changed. We're close in releasing a v1.8.x version of both our API and Wrapper. That should be auto updated on Packagist.
