### ISSUE TITLE
Reissue no message

### ISSUE THREAD

**Issue by rcompier** [xolphin/xolphin-api-php#14]
Whenever I created the CSR Request key and use it to reissue on the test environment I get an error {"message":"An unknown error occurred."}

![image](https://user-images.githubusercontent.com/21107109/52347925-664c2900-2a23-11e9-9821-4da91c6d9a73.png)

All variables are filled in correctly and when dumping them they are indeed filled.
The error occurs on the line to reissue the certificate.

I thought the problem could be because on initializing the client I used client(Username, Password, true) which works for receiving all request and certificates.
There was also no information I could find about something related to this nor a lot about this api in general.

If there is anything unclear or needs further explanation, ask me because I can't wrap my head around this one.

**Comment by XolphinIvo** [comment]
I can't see anything wrong with the code you have posted, other than maybe the variables are undeclared, but that isn't likely (I guess). Can you send a mail to api@xolphin.com with this question (and maybe more of your written code)? Then we can check the logs if we find anything odd for requests on your account, or even debug internally.
