### ISSUE TITLE
Download format doesn't support all

### ISSUE THREAD

**Issue by bedrijfsportaal** [xolphin/xolphin-api-php#17]
Doesn't Xolphin support the download of p7b (Windows) and .ics (Calendar)? All other formats work as example in your own website but it doesn't seem to be supported in the API.

File: src\Endpoint\Certificate.php
Line: 57-61

@XolphinIvo 
It would be great if other formats are supported as well, i'm also missing the root certificates download?

**Comment by XolphinIvo** [comment]
Regarding the possibility to download the root certificate(s). This can be done using the /certificate/{id}/download endpoint. In the wrapper, you can call the download($id, $format) method on the Certificate object. By default, it will download the certificate itself, but the $format parameter can be used to download the root and intermediate certs. Use the option CA_BUNDLE for this. All supported formats are stated in our documentation on https://api.xolphin.com/docs/v1#/certificate/get_certificates__id__download

Regarding the possibility to offer a p7b download, our api doesn’t have this option yet. I will create an internal ticket for us, so it will be implemented in a later version of our API (and wrapper).

**Comment by bedrijfsportaal** [comment]
And the .ics (calendar)?

**Comment by ghost** [comment]
The .ics is available for download in our ControlPanel only and not trough our API's (therefore it is not in our wrappers).

**Comment by bedrijfsportaal** [comment]
Thank you for the response.
