### ISSUE TITLE
Packagist niet up-to-date

### ISSUE THREAD

**Issue by martijngastkemper** [xolphin/xolphin-api-php#2]
Op Packagist staat niet de laatste versie. Ik vermoed dat GitHub niet automatisch de wijzigingen naar Packagist pusht. Hiervoor kan GitHub Services Hooks gebruikt worden: https://packagist.org/about#how-to-update-packages.

**Comment by xolphin** [comment]
Bedankt voor het doorgeven. Als het goed is is dat nu opgelost?

**Comment by martijngastkemper** [comment]
Ja het is opgelost. Thanks voor de snelle reactie.
