### ISSUE TITLE
Package not yet fully updated for the upcoming changes?

### ISSUE THREAD

**Issue by dvdheiden** [xolphin/xolphin-api-php#36]
Hi!

We've received the message about the upcoming changes and I wanted to implemented those changes asap. But I have the idea that this package hasn't been fully updated yet.

According to the document with the upcoming changes:

> 4.1.1 REST [POST] /requests
> REST [POST] /certificates/{id}/reissue
> REST [POST] /certificates/{id}/renew
> The parameter “approverRepresentativeEmail” must be provided on all OV/EV orders from
> January 15, 2024 within the Xolphin API, for all OV/EV SSL, code signing, and PDF signing
> requests. Please update these variables as soon as possible.

I do see that the [CertificateRequest](https://github.com/xolphin/xolphin-api-php/blob/master/src/Requests/CertificateRequest.php) class has been updated, but the [RenewRequest](https://github.com/xolphin/xolphin-api-php/blob/master/src/Requests/RenewRequest.php) class and the [ReissueRequest](https://github.com/xolphin/xolphin-api-php/blob/master/src/Requests/ReissueRequest.php) class seem not to be updated as those are still missing the `approverRepresentativeEmail`.

So I was wondering if I'm not fully understanding the changes or this package still needs an additional update to be prepared for the upcoming changes.

**Comment by ohalessl247** [comment]
Hello,
Good spot, those endpoints shall be updated by the end of today.

**Comment by dvdheiden** [comment]
Wow, that's quick! Thank you and I'm looking forward to the new version!
