### ISSUE TITLE
Too Many Requests: Rate limit exceeded  

### ISSUE THREAD

**Issue by cmodijk** [xolphin/xolphin-api-php#4]
When i try to run the unit tests i'm getting rate limit error's. Maybe it is easers to mock all the request to give fake results?

```
Too Many Requests: Rate limit exceeded  
```

**Comment by xolphin** [comment]
You are absolutely right. We will make the required changes on our side, but give us a couple of days to implement this. I will get back to you as soon as it is done.

**Comment by doenietzomoeilijk** [comment]
Is there any chance of this getting some love again? I'd love to see the change in issue #5  implemented but it seems to have stagnated.

**Comment by XolphinIvo** [comment]
It's been a while, but I'm working on proper unit tests with mocked data. I hope to implement this somewhere in the next weeks.

**Comment by ghost** [comment]
Our API Rate Limit has been extended to 3600 calls an hour. Our current Unittest suite uses 23 calls. Our current Rate Limit allows you to run it completely roughly 3 times a minute.
